### ISSUE TITLE
add an readme

### ISSUE THREAD

**Issue by RedSpeeds** [ferrybig/DiamondRails#1]
please add a readme because i need this plugin but i dont know how to use it

**Comment by calvinn** [comment]
Can you make that its word with traincarts

**Comment by RedSpeeds** [comment]
calvinn it already works with traincart just place the function signs on top of the ore

**Comment by calvinn** [comment]
can you make a screen where i must place

**Comment by calvinn** [comment]
How i can this as a .jar or have you its as a jar?

**Comment by RedSpeeds** [comment]
you use git to clone this respertory

**Comment by calvinn** [comment]
But idk how i make it to a .jar and do you have a screen where and how i place te sign
